# Builtins

Rebo is released with a number of builtin functions. These functions are always available and are attached to the top-level scope.

**Note:** It is possible to redefine these functions in your own code, but this is not recommended.  For example, to replace `gc` so that it prints the duration of the garbage collection, you could do the following:

```rebo
let _gc = gc

gc := fn() {
   let stats = _gc()
   
   println("GC duration: ", stats.duration, "ms")

   stats
}

gc()
```

The builtin functions are divided into the following categories:

- Core Language
- OS Interfaces
- I/O Interfaces
- Math
- Runtime Support

## Core Language

### import(file)

### imports()

### int(value, default = (), base = 10)

### len(value)

### print(...values = [])

### println(...values = [])

### str(value, literal = false)

### typeof(value = ())

## OS Interfaces

Exposes services that are provided by the operating system.

### cwd()

Returns the current working directory as a string.

```rebo
cwd()
```

### ls(path = ".")

Returns a sequence of files and directories in the given path.  Should the path not exist or not be readable, an empty sequence is returned.

```rebox
ls()
ls(cwd())
```

### milliTimestamp()

## Runtime Support

Provides access to runtime information and services.

### exit(code = 0)

Immediately exits the program with the given exit code.

```rebo
exit()
```

Should `code` be anything other than an integer, it will be converted to a string, printed to stderr and exit with exit code 1.

```rebo
exit("Invalid number of arguments")
```

### gc()

Runs the garbage collector and returns the memory statistics.

```rebo
gc()
```

### rebo

