pub const Op = enum(u8) {
    ret,
    push_char,
    push_int,
    push_false,
    push_float,
    push_record,
    push_sequence,
    push_string,
    push_true,
    push_unit,

    jmp,
    jmp_true,
    jmp_false,

    duplicate,
    discard,

    append_sequence_item_bang,
    append_sequence_items_bang,

    set_record_item_bang,
    set_record_items_bang,

    equals,
    not_equals,
    less_than,
    less_equal,
    greater_than,
    greater_equal,
    add,
    subtract,
    multiply,
    divide,
    modulo,
    seq_append,
    seq_append_bang,
    seq_prepend,
    seq_prepend_bang,
};
