name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.13.0 # released versions or master

      - name: Test Build
        run: |
          zig build test

      - name: Test Rebo suite and markdown code blocks
        run: |
          zig build run -- ./bin/rebo-test

  'upload-x86_64-linux-artefacts':
    runs-on: ubuntu-latest
    needs: 
      - build

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.13.0 # released versions or master
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build -target x86_64-linux    
        run: |
          zig build-exe ./src/main.zig -O ReleaseFast -fstrip
    
      - name: Upload x86_64-linux artifact
        run: |
          az storage blob upload \
            --account-name littlelanguages \
            --container-name rebo \
            --name x86_64-linux \
            --type block \
            --tier hot \
            --file ./main --overwrite

  'upload-x86_64-darwin-artefacts':
    runs-on: macos-13
    needs: 
      - build

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.13.0 # released versions or master
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build target
        run: |
          zig build-exe ./src/main.zig -O ReleaseFast -fstrip
    
      - name: Upload x86_64-darwin artifact
        run: |
          az storage blob upload \
            --account-name littlelanguages \
            --container-name rebo \
            --name x86_64-darwin \
            --type block \
            --tier hot \
            --file ./main --overwrite


  'upload-aarch64-darwin-artefacts':
    runs-on: macos-14
    needs: 
      - build

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.13.0 # released versions or master
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build target
        run: |
          zig build-exe ./src/main.zig -O ReleaseFast -fstrip
    
      - name: Upload x86_64-darwin artifact
        run: |
          az storage blob upload \
            --account-name littlelanguages \
            --container-name rebo \
            --name aarch64-darwin \
            --type block \
            --tier hot \
            --file ./main --overwrite
