name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.11.0 # released versions or master

      - name: Test Build
        run: |
          cd ./rebo
          zig build test

      - name: Test Rebo
        run: |
          cd ./rebo
          zig build run -- ./test/suite.rebo
